version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8080"
    depends_on:
      - mysql
      - mongo
      - redis
    environment:
      DB_URL: jdbc:mysql://mysql:3306/backendapi
      DB_USER: root
      DB_PASSWORD: password
      MONGO: pokemon


  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: backendapi
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data:
  mongo_data:
